[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools", "python310Packages.wheel", "postgresql"]
nixLibs = ["gcc-unwrapped"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt --no-cache-dir"]

[phases.build]

[start]
cmd = "cd backend && python manage.py migrate && gunicorn twitter_clone.wsgi --bind 0.0.0.0:$PORT"
