[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.virtualenv", "postgresql"]

[phases.install]
cmds = [
    "cd backend && python -m venv /opt/venv",
    "cd backend && /opt/venv/bin/pip install --upgrade pip",
    "cd backend && /opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]

[start]
cmd = "cd backend && /opt/venv/bin/python manage.py migrate && /opt/venv/bin/gunicorn twitter_clone.wsgi --bind 0.0.0.0:$PORT"
