[phases.setup]
nixPkgs = ["python310Full", "postgresql"]

[phases.install]
cmds = ["cd backend && python3.10 -m ensurepip", "cd backend && python3.10 -m pip install -r requirements.txt"]

[phases.build]

[start]
cmd = "cd backend && python3.10 manage.py migrate && python3.10 -m gunicorn twitter_clone.wsgi --bind 0.0.0.0:$PORT"
