[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "postgresql"]

[phases.install]
cmds = ["cd backend && python -m pip install --upgrade pip", "cd backend && python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["cd backend && python manage.py collectstatic --noinput || true"]

[start]
cmd = "cd backend && python manage.py migrate && gunicorn twitter_clone.wsgi --bind 0.0.0.0:$PORT"
